package com.bank.islamic.aaoififinancialaccounting;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: AAOIFI Financial Accounting
 *
 * Business Area:      Takaful and Shared Operations
 * Business Domain:    Shared Operations
 * Functional Pattern: Process
 * Asset Type:         AAOIFI Ledger Posting
 * Control Record:     AAOIFI Ledger Posting Procedure
 *
 * Generated by the islamic-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("AAOIFI Financial Accounting — BIAN Semantic API")
                .description("Service Domain 'AAOIFI Financial Accounting' (Process pattern) "
                        + "operating on the 'AAOIFI Ledger Posting Procedure' control record.")
                .version("0.1.0"));
    }
}
